import { invoke } from "@tauri-apps/api/core";
import "./styles.css";

type AppState = { profileExists: boolean };
type Page = "home" | "chats" | "friends" | "groups" | "settings";
type Chat = { name: string; handle: string; preview: string; time: string; unread?: number; initials: string; color: string };

const app = document.querySelector<HTMLElement>("#app")!;
const sampleChats: Chat[] = [
  { name: "Maya Chen", handle: "@maya", preview: "That sounds perfect — see you then.", time: "10:42", initials: "MC", color: "coral", unread: 2 },
  { name: "Design circle", handle: "4 members", preview: "Jon: I added the notes to the board.", time: "09:18", initials: "DC", color: "violet" },
  { name: "Owen Wright", handle: "@owen", preview: "Photo", time: "Yesterday", initials: "OW", color: "blue" },
];

let page: Page = "home";
let selectedChat = 0;
let demoMode = false;
let composerMessages = ["Hi Maya! I saved a few thoughts for our meeting.", "Great — I’ll take a look before lunch."];

async function render() {
  const state = await invoke<AppState>("app_state").catch(() => ({ profileExists: false }));
  app.innerHTML = state.profileExists || demoMode ? workspace() : onboarding();
  bindEvents();
}

function onboarding() {
  return `<section class="onboarding"><div class="onboarding-copy"><p class="eyebrow">HEARTH · LOCAL-FIRST MESSAGING</p><h1>A calm place for the people you trust.</h1><p class="lede">Create a local identity to start using Hearth. Prefer to look around first? Open the clearly labelled sample workspace — it never connects to a service or sends a message.</p><div class="trust-points"><span>Local SQLite profile</span><span>•</span><span>No account required to preview</span></div></div><div class="identity-card"><div class="card-heading"><span class="brand-mark">H</span><div><h2>Create your local identity</h2><p>Saved only on this device.</p></div></div><form id="identity-form"><label>Username<input name="username" autocomplete="username" placeholder="ada_lovelace" required minlength="3" maxlength="32" pattern="[a-zA-Z0-9_]+" /></label><label>Display name<input name="displayName" autocomplete="name" placeholder="Ada Lovelace" required maxlength="64" /></label><button type="submit">Create local identity <span aria-hidden="true">→</span></button><p id="form-error" class="form-error" role="alert"></p></form><div class="divider"><span>or</span></div><button class="secondary" type="button" data-action="demo">Explore test mode</button><p class="fineprint">Test mode uses sample content in this window only. It does not create an identity, persist messages, or claim networking is enabled.</p></div></section>`;
}

function workspace() {
  const nav = [
    ["home", "Home", "⌂"], ["chats", "Chats", "◌"], ["friends", "People", "♙"], ["groups", "Groups", "◫"],
  ].map(([id, label, icon]) => `<button class="nav-item ${page === id ? "active" : ""}" data-page="${id}" aria-current="${page === id ? "page" : "false"}"><span aria-hidden="true">${icon}</span>${label}</button>`).join("");
  return `<section class="app-shell"><aside class="sidebar"><div class="sidebar-top"><div class="brand"><span class="brand-mark">H</span><span>Hearth</span></div><button class="icon-button mobile-close" aria-label="Close navigation">×</button></div><nav aria-label="Main navigation">${nav}</nav><div class="sidebar-bottom"><button class="profile-button" data-page="settings"><span class="avatar small green">A</span><span><strong>${demoMode ? "Sample workspace" : "Your workspace"}</strong><small>${demoMode ? "Test mode" : "Local profile"}</small></span><span aria-hidden="true">•••</span></button><p class="connection"><span></span>${demoMode ? "Sample content only" : "Offline · local workspace"}</p></div></aside><main class="content"><header class="topbar"><button class="icon-button menu-button" data-action="menu" aria-label="Open navigation">☰</button><div class="breadcrumb"><span class="eyebrow">${demoMode ? "TEST MODE" : "LOCAL WORKSPACE"}</span><h2>${pageTitle()}</h2></div><div class="top-actions"><button class="icon-button" data-page="settings" aria-label="Open settings">⚙</button><button class="avatar small orange" aria-label="Account menu">A</button></div></header>${pageContent()}</main></section>`;
}

function pageTitle() { return ({ home: "Good morning", chats: "Messages", friends: "People", groups: "Groups", settings: "Settings" })[page]; }
function pageContent() {
  if (page === "home") return homePage();
  if (page === "chats") return chatsPage();
  if (page === "friends") return peoplePage();
  if (page === "groups") return groupsPage();
  return settingsPage();
}
function homePage() { return `<div class="page home"><section class="hero"><div><p class="eyebrow">YOUR SPACE</p><h1>Keep close to what matters.</h1><p>Hearth is designed around your device and your relationships. ${demoMode ? "You are viewing sample content, so every interaction stays local to this preview." : "Set up your local identity, then follow the delivery roadmap as services become available."}</p><button data-page="chats">${demoMode ? "View sample chats" : "Explore workspace"} <span aria-hidden="true">→</span></button></div><div class="hero-art" aria-hidden="true"><span class="orb orb-one"></span><span class="orb orb-two"></span><span class="message-shape">hello</span><span class="message-shape second">there</span></div></section><section class="section-head"><div><p class="eyebrow">AT A GLANCE</p><h3>Today in Hearth</h3></div><button class="text-button" data-page="chats">All messages</button></section><div class="stat-grid"><article><span class="stat-icon amber">◌</span><strong>${demoMode ? "3" : "0"}</strong><p>Conversations</p></article><article><span class="stat-icon plum">♙</span><strong>${demoMode ? "5" : "0"}</strong><p>People</p></article><article><span class="stat-icon blue">◫</span><strong>${demoMode ? "1" : "0"}</strong><p>Groups</p></article></div><section class="section-head recent"><div><p class="eyebrow">RECENT</p><h3>${demoMode ? "Continue a conversation" : "Your workspace is ready"}</h3></div></section>${demoMode ? `<div class="recent-list">${sampleChats.slice(0, 2).map((chat, i) => chatRow(chat, i)).join("")}</div>` : `<div class="empty-state compact"><span class="empty-icon">✦</span><div><strong>No conversations yet</strong><p>Messaging remains unavailable until its encrypted transport is implemented.</p></div></div>`}</div>`; }
function chatsPage() { const chat = sampleChats[selectedChat]; return `<div class="chat-page"><section class="conversation-list"><div class="list-header"><div><p class="eyebrow">INBOX</p><h3>Messages</h3></div><button class="round-button" disabled aria-label="New conversation unavailable">+</button></div><label class="search"><span aria-hidden="true">⌕</span><input placeholder="Search conversations" aria-label="Search conversations" /></label>${demoMode ? `<div class="chat-list">${sampleChats.map((item, i) => chatRow(item, i)).join("")}</div>` : `<div class="empty-state"><span class="empty-icon">◌</span><strong>No conversations</strong><p>Encrypted direct messaging is planned for Phase 5.</p></div>`}</section><section class="thread">${demoMode ? `<header class="thread-header"><div class="avatar ${chat.color}">${chat.initials}</div><div><h3>${chat.name}</h3><p>${chat.handle} · Sample conversation</p></div><button class="icon-button" aria-label="Conversation details">⋮</button></header><div class="message-feed"><p class="date-label">TODAY</p><div class="bubble incoming">Hi! Are we still on for the planning session?</div>${composerMessages.map(message => `<div class="bubble outgoing">${escapeHtml(message)}</div>`).join("")}<div class="typing-note">Sample content · no message has been sent</div></div><form class="composer" id="composer"><button class="icon-button" type="button" aria-label="Attachments" title="Attachments are not available in test mode">+</button><input name="message" autocomplete="off" placeholder="Write a sample reply" aria-label="Write a sample reply" maxlength="500" /><button type="submit" aria-label="Add local sample reply">↑</button></form>` : `<div class="empty-thread"><span class="empty-icon">✦</span><h3>Select a conversation</h3><p>When encrypted delivery is implemented, messages will be persisted locally before they leave this device.</p></div>`}</section></div>`; }
function peoplePage() { return `<div class="page"><section class="page-intro"><p class="eyebrow">PEOPLE</p><h1>People, with trust at the center.</h1><p>Discovery, requests, blocks, and identity verification need the coordination service from Phase 3 and Phase 7. They are not simulated here.</p></section><div class="feature-grid"><article><span>⌕</span><h3>Find people</h3><p>Username discovery will verify a public identity, not just an alias.</p><button disabled>Search coming later</button></article><article><span>✓</span><h3>Requests</h3><p>Friend requests will require an explicit acceptance before messaging.</p><button disabled>Requests unavailable</button></article></div></div>`; }
function groupsPage() { return `<div class="page"><section class="page-intro"><p class="eyebrow">GROUPS</p><h1>Shared spaces without a central history.</h1><p>Group membership and messages will use MLS epochs and replicated encrypted state. This screen intentionally has no create control until that system exists.</p></section><div class="empty-state wide"><span class="empty-icon">◫</span><strong>No groups yet</strong><p>Groups are scheduled after direct messaging, offline delivery, and friends.</p></div></div>`; }
function settingsPage() { return `<div class="page settings"><section class="page-intro"><p class="eyebrow">SETTINGS</p><h1>Workspace settings</h1><p>Settings shown here describe the current application boundary.</p></section><div class="settings-list"><article><div><h3>Connection</h3><p>${demoMode ? "Test mode never opens a network connection." : "Offline. Networking has not been configured."}</p></div><span class="pill neutral">${demoMode ? "Sample" : "Offline"}</span></article><article><div><h3>Storage</h3><p>${demoMode ? "Sample messages are held only in this browser window." : "Your profile is stored in local SQLite."}</p></div><span class="pill good">Local</span></article><article><div><h3>Development preview</h3><p>Use test mode to inspect all workspace pages without creating an identity.</p></div><button class="secondary small-button" data-action="demo">${demoMode ? "Restart preview" : "Open test mode"}</button></article></div></div>`; }
function chatRow(chat: Chat, index: number) { return `<button class="chat-row ${selectedChat === index && page === "chats" ? "selected" : ""}" data-chat="${index}"><span class="avatar ${chat.color}">${chat.initials}</span><span class="chat-copy"><strong>${chat.name}</strong><small>${chat.preview}</small></span><span class="chat-meta"><small>${chat.time}</small>${chat.unread ? `<b>${chat.unread}</b>` : ""}</span></button>`; }
function escapeHtml(value: string) { const element = document.createElement("span"); element.textContent = value; return element.innerHTML; }

function bindEvents() {
  document.querySelector<HTMLFormElement>("#identity-form")?.addEventListener("submit", createIdentity);
  document.querySelector<HTMLFormElement>("#composer")?.addEventListener("submit", addSampleMessage);
  document.querySelectorAll<HTMLElement>("[data-page]").forEach(button => button.addEventListener("click", () => { page = button.dataset.page as Page; render(); }));
  document.querySelectorAll<HTMLElement>("[data-chat]").forEach(button => button.addEventListener("click", () => { selectedChat = Number(button.dataset.chat); page = "chats"; render(); }));
  document.querySelectorAll<HTMLElement>("[data-action=demo]").forEach(button => button.addEventListener("click", () => { demoMode = true; page = "home"; render(); }));
  document.querySelector<HTMLElement>("[data-action=menu]")?.addEventListener("click", () => document.querySelector(".sidebar")?.classList.toggle("open"));
}
async function createIdentity(event: SubmitEvent) { event.preventDefault(); const form = event.currentTarget as HTMLFormElement; const values = new FormData(form); const error = document.querySelector<HTMLElement>("#form-error")!; try { await invoke("create_profile", { username: values.get("username"), displayName: values.get("displayName") }); demoMode = false; await render(); } catch (reason) { error.textContent = String(reason); } }
function addSampleMessage(event: SubmitEvent) { event.preventDefault(); const input = new FormData(event.currentTarget as HTMLFormElement).get("message"); if (typeof input === "string" && input.trim()) { composerMessages.push(input.trim()); render(); } }
render();
